### ISSUE TITLE
POE-5 MIPS64 平台，使用后报错了

### ISSUE THREAD

**Issue by xqiushi** [imMMX/chn_iptables#3]
POE-5 MIPS64 平台，使用后报错了，内国网站打开也慢了。固件2.0.1
```
error: <class 'socket.error'>, [Errno 13] Permission denied: file: /usr/lib/python2.7/socket.py line: 228
```

**Comment by xqiushi** [comment]
现在的主要问题集中在xt_TPROXY上了呢。他面的错误是因为测试的时候没有用sudo

**Comment by m2nx** [comment]
嗯. 没太理解。直接在机器上编译的？

**Comment by xqiushi** [comment]
> 嗯. 没太理解。直接在机器上编译的？

难道是下载一个debian,交叉编译?
这里有xt_TPROXY的编译源码吗?

**Comment by m2nx** [comment]
几个文件夹下的 xt_TPROXY 都试试看看。

**Comment by xqiushi** [comment]
> 几个文件夹下的 xt_TPROXY 都试试看看。

USG的还没有试,我估计最终会选增加一个旁路由来实现这些功能.

**Comment by xqiushi** [comment]
目前旁路由，准备编辑一个openwrt试试
